### ISSUE TITLE
Find solution for indentation

### ISSUE THREAD

**Issue by severdia** [severdia/shakespeare-obsidian#5]
It appears the indentation doesn't work in Obsidian reading mode so we need to figure out a solution for this. Right now, the XML files have an `offset` value of 0-10 indicating the number of indents for that line. When XML is converted to markdown, the `&emsp;` character is added to show the indentation based on the following:

```
offset 2  (4 x &emsp;)
offset 3  (8 x &emsp;)
offset 4  (11 x &emsp;)
offset 5  (14 x &emsp;)
offset 6  (16 x &emsp;)
offset 7  (18 x &emsp;)
offset 8  (21 x &emsp;)
offset 9  (23 x &emsp;)
offset 10  (25 x &emsp;)

```

**Comment by mmkon** [comment]
The solution for this problem:

1. add the following css code into "Shakespeare Styles.css" css snippet file:
```css
.markdown-preview-view p {
	white-space: pre-wrap;
}
```
2. In Obsidian turn ON the "Editor / Strict Line Breaks" setting.

![1](https://github.com/severdia/shakespeare-obsidian/assets/8308184/f1dcf317-32c0-43f3-ab47-31c7eaffe3e9)
